# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: mongojhip

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

spring:
    mail:
        from: panosvlastaridis@gmail.com
        host: smtp.gmail.com
        port: 587
        user: panosvlastaridis@gmail.com
        password: ********
        protocol: smtp
        tls: true
        auth: true

    messageSource:
        cacheSeconds: 1

swagger:
    title: mongojhip API
    description: mongojhip applications and beyond!
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
